[tool.poetry]
name = "wavy-totem-lib"
version = "1.1.0"
description = "Python library to generate totems of undying for Minecraft"
authors = ["wavy-cat <52543076+wavy-cat@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^10.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
