name: Docs

on:
  push:
    branches:
      - main
      - docs

permissions:
    contents: write

jobs:
  docs-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs/_build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          allow_empty_commit: true
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/